### ISSUE TITLE
Only `started` and `completed` events are sent to the weblog endpoint

### ISSUE THREAD

**Issue by robsyme** [nextflow-io/nf-weblog#10]
When running 

```
NXF_VER=23.10.0 nextflow run hello -with-weblog
```

and the dummy python server [here](https://gist.github.com/robsyme/e1219ad4e7a7ae210199d9aaf5f96fcc), only `"event":"completed"` and `"event":"started"` are sent to the server. No `process_submitted`, `process_started`, or `process_completed` events are sent.

**Comment by bentsherman** [comment]
This is with the latest version of the weblog plugin?

**Comment by robsyme** [comment]
Yes - I ran `rm -r ~/.nextflow/assets/nf-weblog-1.1.1` before running

**Comment by bentsherman** [comment]
This one was tricky. We encountered this issue several months ago and fixed it with a change in Nextflow 23.08.0-edge. But I guess because the plugin explicitly uses 23.07.0-edge in the build system, it didn't incorporate this fix.

Tested and fixed in 1.1.2
