### ISSUE TITLE
New feature: add Basic Auth 

### ISSUE THREAD

**Issue by redbass** [nextflow-io/nf-weblog#2]
I'm working on a bit of software that uses `weblog` against an AWS lambda. For security reasons, I need to enable any type of authentication.

I've noticed that  Nextflow `SimpleHttpClient` works ([link](https://github.com/nextflow-io/nextflow/blob/8a4348939949ce5532179cc8067350c9c2c598ef/modules/nextflow/src/main/groovy/nextflow/util/SimpleHttpClient.groovy#L232)) that is used by `nf-weblog` already supports Basic authentication and update this plugin with a new bit of configuration to use `httpClient.setBasicToken`.

I've forked the code and added some code changes that should allow this new bit of functionality
https://github.com/nextflow-io/nf-weblog/compare/master...redbass:nf-weblog:add-basictoken-auth?expand=1

Please let me know what is the best way to discuss this solution, my company really needs this bit of functionality to complete our product.

**Comment by pditommaso** [comment]
Feel free to submit a PR yo evaluate the impact of your changes

**Comment by redbass** [comment]
Thanks

here is my Pull Request https://github.com/nextflow-io/nf-weblog/pull/3
