### ISSUE TITLE
missing process signals

### ISSUE THREAD

**Issue by tuncayseker** [nextflow-io/nf-weblog#6]
After the integration of the nf-weblog plugin, http endpoint could not receive the process (started, completed etc.) signals. I tried all versions after the 23.06.0-edge release.  (23.06.0-edge version is ok). Only workflow started and completed signals are sent. Is it expected behavior?

**Comment by kmotoko** [comment]
@bentsherman could you confirm that this is indeed a bug in the plugin, otherwise I'm going to open an issue in the main nextflow repo

Thanks in advance

**Comment by bentsherman** [comment]
This issue was [fixed](https://github.com/nextflow-io/nextflow/commit/07582f0b7361745e5ef100598a189c881a033062) in 23.09.0-edge

**Comment by bentsherman** [comment]
Sorry, turns out the plugin also needed to be updated to incorporate the fix from Nextflow. Fixed in 1.1.2
